version: '3.8'
services:
 dev-db:
  image: postgres:13
  ports:
   - 5444:5432
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: mrhappy
  networks:
    - mynetwork
networks:
 mynetwork: